////
Copyright 2020 Aaron Brown

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
////
= Dumb Reports
:toc:

*Dumb Reports* is a JVM Library for creating dumb,
simple reports programmatically. The interfaces are
meant to be simple, and there are some packaged
implementations.

If you want fancy reports, you probably want to use
something else. But if you want dumb reports, then
you're in the right place.

== Projects

[cols="m,d", options="header"]
.Projects
|===
|Project
|Description

|link:dumb-reports[dumb-reports]
|The core project, which contains the basic
 interfaces.

|link:dumb-reports-slf4j[dumb-reports-slf4j]
|An implementation of `dumb-reports` that wraps an
 SLFJ4 Logger into a Report so you can `log` while
 you report.

 Useful for if your use-case is very limited and you
 are okay with bad ideas.

|link:dumb-reports-status[dumb-reports-status]
|An implementation of `dumb-reports` that can be used
 and extended for making status reports.

|link:spring-dumb-reports-starter[spring-dumb-reports-starter]
|A Spring-Boot Starter for `dumb-reports`.

|link:spring-dumb-reports-example[spring-dumb-reports-example]
|A spring-Boot example projet that demonstrates
 `dumb-reports`.
|===

== Version History

0.0.1::
* Still in development
* Started `dumb-reports`
* Started `dumb-reports-slf4j`
* Started `dumb-reports-status`
* Started `spring-dumb-reports-starter`
* Started `spring-dumb-reports-example`
** Added an example for `dumb-reports-slf4j`
** Added an example for `dumb-reports-status`