////
Copyright 2020 Aaron Brown

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
////
= Spring Dumb Reports Starter

This Spring Boot Starter will get you started using `dumb-reports`, and
comes with packaged Auto-Configurations for each of the implementations
found in this Project.

== Getting Started

To get access to the `dumb-reports` (base) library, simply include this in
your `build.gradle`:

[source,groovy]
.build.gradle
----
dependencies {
    implementation 'com.aarocode:spring-dumb-reports-starter'
}
----

Auto-Configuration for packaged classes depends on if you include them;
they do _not_ come with this Starter:

[source,groovy]
.build.gradle
----
dependencies {
    implementation 'com.aarocode:spring-dumb-reports-starter'

    implementation 'com.aarocode:dumb-reports-status'
}
----

The above will include and Auto-Configure `dumb-reports-status`, but not
include / Auto-Configure `dumb-reports-slf4j`

After including, you may use the respective *Factory* that comes with the
packaged Library, or you have the interfaces to create your own *Report*.